# Занятие 2. Array

## 1. Работа с векторами

В рамках этого раздела мы рассмотрим базовые возможности библиотеки numpy, которая позволяет эффективным образом работать с векторами, матрицами и тензорами.

Для начала подключим библиотеку numpy:

In [2]:
import numpy as np

### 1.1. Работа с одномерными массивами

#### Создание вектора по строкам/столбцам

Создадим вектор небольшого размера по строкам:

In [ ]:
vec1 = np.array([3,6,7,2,4,5])
vec1  # так же можно выводить через print

array([3, 6, 7, 2, 4, 5])

Создадим вектор небольшого размера по столбцам:

In [ ]:
vec2 = np.array([[3],[6],[7],[2],[4],[5]])
vec2

array([[3],
       [6],
       [7],
       [2],
       [4],
       [5]])

#### Создание вектора из элементов прогрессии

Рассмотрим функцию, которая позволяет создать вектор из элементов арифметической прогрессии от -10 включительно до 10.01 невключительно с шагом 0.01:

In [ ]:
x = np.arange(-10, 10.01, 0.01)
x

array([-10.  ,  -9.99,  -9.98, ...,   9.98,   9.99,  10.  ])

#### Создание вектора со случайными элементами

Выполним инициализацию генератора случайных чисел с помощью seed:

In [ ]:
np.random.seed(0)

Создадим вектор длины 15 со случайными элементами, значения которых варьируются от 0.0 до 1.0:

In [ ]:
vec3 = np.random.random(15)
vec3

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

Создадим вектор длины 15 со случайными элементами, значения которых варьируются от 0 включительно до 21 невключительно:

In [5]:
vec3 = np.random.randint(0, 21, 15)
vec3

array([14, 13, 11, 10, 16, 16, 13,  3,  0, 15,  7,  0, 18,  5,  9])

Создадим вектор длины 15 со случайными элементами из нормального распределения с математическим ожиданием 0.0 и среднеквадратическим отклонением 1.0:

In [ ]:
vec3 = np.random.normal(0.0, 1.0, 15)
vec3

array([ 0.3130677 , -0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ,
       -0.74216502,  2.26975462, -1.45436567,  0.04575852, -0.18718385,
        1.53277921,  1.46935877,  0.15494743,  0.37816252, -0.88778575])

#### Работа со срезами

Поработаем со срезами векторов. Вам необходимо самостоятельно выполнить следующие задачи:
1. Получить срез массива после 5-го элемента
2. Получить срез до 10-го элемента
3. Получить срез между 3-м и 12-м элементами
4. Достать последний и предпоследний элементы
5. Удалить элементы от 4-го до 8-го
6. Удалить каждый 2-ой элемент

In [ ]:
# Получить срез массива после 5-го элемента
arr = np.arange(1, 11, 1)
print(arr)
arr[5::]

[ 1  2  3  4  5  6  7  8  9 10]


array([ 6,  7,  8,  9, 10])

In [ ]:
# Получить срез до 10-го элемента
arr = np.arange(1, 16, 1)
print(arr)
arr[:10:]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Получить срез между 3-м и 12-м элементами
arr = np.arange(1, 21)
print(arr)
arr[2:12]


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# Достать последний и предпоследний элементы
arr = np.arange(1, 11)
last_elem = arr[-1]
second_last_elem = arr[-2]

print("Исходный массив:", arr)
print("Последний элемент:", last_elem)
print("Предпоследний элемент:", second_last_elem)

Исходный массив: [ 1  2  3  4  5  6  7  8  9 10]
Последний элемент: 10
Предпоследний элемент: 9


In [ ]:
# Удалить элементы от 4-го до 8-го
arr = np.arange(1, 21)
new_arr = np.delete(arr, np.s_[3:8])

print("Исходный массив:", arr)
print("Массив после удаления элементов с 4-го по 8-й:", new_arr)

Исходный массив: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Массив после удаления элементов с 4-го по 8-й: [ 1  2  3  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# Удалить каждый 2-ой элемент
arr = np.arange(1, 21)
new_arr = arr[::2]

print("Исходный массив:", arr)
print("Массив после удаления каждого второго элемента:", new_arr)

Исходный массив: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Массив после удаления каждого второго элемента: [ 1  3  5  7  9 11 13 15 17 19]


### 1.2. Работа с матрицами

#### Создание двумерного массива (матрицы)

Попробуем создать двумерный массив:

In [ ]:
mat1 = np.array([[2,4,6],[-3,5,1],[1,1,1],[7,4,5]])
mat1

array([[ 2,  4,  6],
       [-3,  5,  1],
       [ 1,  1,  1],
       [ 7,  4,  5]])

Аналогичным образом можно создать матрицу - это тот же двумерный массив, только с особенностями, характерными для матриц (например, операция * задает матричное умножение):

In [ ]:
mat2 = np.mat([[2,4,6],[-3,5,1],[1,1,1],[7,4,5]])
mat2

matrix([[ 2,  4,  6],
        [-3,  5,  1],
        [ 1,  1,  1],
        [ 7,  4,  5]])

#### Использование свойств массива

Выведите самостоятельно количество строк и столбцов (метод shape), количество элементов (size) и количество размерностей (ndim) у созданного массива.

In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

print("Матрица:")
print(matrix)


print("Количество строк и столбцов (shape):", matrix.shape)
print("Количество элементов (size):", matrix.size)
print("Количество размерностей (ndim):", matrix.ndim)

Матрица:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Количество строк и столбцов (shape): (4, 3)
Количество элементов (size): 12
Количество размерностей (ndim): 2


#### Получение статистических данных

Выполните следующие задачи для одномерного вектора и двумерного массива (матрицы):
1. Найдите максимум, минимум, среднее (mean), дисперсию (var) и стандартное отклонение (std). В numpy есть для этого уже готовые методы.
2. Выполните сортировку массива.

In [ ]:
vector = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

max_value = np.max(vector)
min_value = np.min(vector)
mean_value = np.mean(vector)
var_value = np.var(vector)
std_value = np.std(vector)

sorted_vector = np.sort(vector)

print("Одномерный вектор:", vector)
print("Максимум:", max_value)
print("Минимум:", min_value)
print("Среднее:", mean_value)
print("Дисперсия:", var_value)
print("Стандартное отклонение:", std_value)
print("Отсортированный вектор:", sorted_vector)

Одномерный вектор: [3 1 4 1 5 9 2 6 5 3]
Максимум: 9
Минимум: 1
Среднее: 3.9
Дисперсия: 5.49
Стандартное отклонение: 2.3430749027719964
Отсортированный вектор: [1 1 2 3 3 4 5 5 6 9]


In [ ]:
matrix = np.array([
    [3, 1, 4],
    [1, 5, 9],
    [2, 6, 5]
])


max_value = np.max(matrix)
min_value = np.min(matrix)
mean_value = np.mean(matrix)
var_value = np.var(matrix)
std_value = np.std(matrix)


sorted_matrix = np.sort(matrix, axis=1)


print("Двумерный массив (матрица):")
print(matrix)
print("Максимум:", max_value)
print("Минимум:", min_value)
print("Среднее:", mean_value)
print("Дисперсия:", var_value)
print("Стандартное отклонение:", std_value)
print("Отсортированный массив (по строкам):")
print(sorted_matrix)

Двумерный массив (матрица):
[[3 1 4]
 [1 5 9]
 [2 6 5]]
Максимум: 9
Минимум: 1
Среднее: 4.0
Дисперсия: 6.0
Стандартное отклонение: 2.449489742783178
Отсортированный массив (по строкам):
[[1 3 4]
 [1 5 9]
 [2 5 6]]


#### Применение операции к каждому элементу

Создадим массив из 20 чисел от -5 до 25:

In [ ]:
vec4 = np.linspace(-5, 25, 20)
vec4

array([-5.        , -3.42105263, -1.84210526, -0.26315789,  1.31578947,
        2.89473684,  4.47368421,  6.05263158,  7.63157895,  9.21052632,
       10.78947368, 12.36842105, 13.94736842, 15.52631579, 17.10526316,
       18.68421053, 20.26315789, 21.84210526, 23.42105263, 25.        ])

Попробуем увеличить все значения на 2. Это можно сделать следующим образом:

In [ ]:
add_2 = lambda x: x + 2
a = np.vectorize(add_2)(vec4)  # можно в одну строчку
a

array([-3.        , -1.42105263,  0.15789474,  1.73684211,  3.31578947,
        4.89473684,  6.47368421,  8.05263158,  9.63157895, 11.21052632,
       12.78947368, 14.36842105, 15.94736842, 17.52631579, 19.10526316,
       20.68421053, 22.26315789, 23.84210526, 25.42105263, 27.        ])

Выполните самостоятельно следующие задачи как для вектора, так и для матрицы (векторизованную функцию можно сохранить):
1. Разделите все элементы массива на его максимальный элемент
2. Выполните обнуление всех четных элементов
3. Замените все отрицательные элементы на 0, а положительные удвойте

In [ ]:
vector = np.array([1, 2, 3, 4, 5])
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

divide_by_max = lambda x: x / np.max(x)
vector_normalized = divide_by_max(vector)
matrix_normalized = divide_by_max(matrix)

print("Вектор после деления на максимальный элемент:")
print(vector_normalized)

print("\nМатрица после деления на максимальный элемент:")
print(matrix_normalized)

Вектор после деления на максимальный элемент:
[0.2 0.4 0.6 0.8 1. ]

Матрица после деления на максимальный элемент:
[[0.11111111 0.22222222 0.33333333]
 [0.44444444 0.55555556 0.66666667]
 [0.77777778 0.88888889 1.        ]]


In [ ]:
zero_even = lambda x: np.where(x % 2 == 0, 0, x)

vector_zero_even = zero_even(vector)
matrix_zero_even = zero_even(matrix)

print("Вектор после обнуления четных элементов:")
print(vector_zero_even)

print("\nМатрица после обнуления четных элементов:")
print(matrix_zero_even)

Вектор после обнуления четных элементов:
[1 0 3 0 5]

Матрица после обнуления четных элементов:
[[1 0 3]
 [0 5 0]
 [7 0 9]]


In [ ]:
vector_with_neg = np.array([-1, 2, -3, 4, -5])
matrix_with_neg = np.array([
    [-1, 2, -3],
    [4, -5, 6],
    [-7, 8, -9]
])

replace_neg_double_pos = lambda x: np.where(x < 0, 0, x * 2)
vector_replaced = replace_neg_double_pos(vector_with_neg)
matrix_replaced = replace_neg_double_pos(matrix_with_neg)

print("Вектор после замены отрицательных и удвоения положительных:")
print(vector_replaced)

print("\nМатрица после замены отрицательных и удвоения положительных:")
print(matrix_replaced)

Вектор после замены отрицательных и удвоения положительных:
[0 4 0 8 0]

Матрица после замены отрицательных и удвоения положительных:
[[ 0  4  0]
 [ 8  0 12]
 [ 0 16  0]]


#### Изменение размерности векторов

Посмотрим, как менять размерность уже созданных массивов. Для начала создадим вектор из 60 чисел:

In [ ]:
a = np.arange(60)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

Далее выполним преобразование к двумерному массиву:

In [ ]:
a1 = a.reshape(2, -1)  # !!! размер
a1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

Выполним аналогичное преобразование к трехмерному массиву:

In [ ]:
a2 = a.reshape(3, 4, -1)
a2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

Создайте самостоятельно матрицу 2 x 12. Преобразуйте в трёхмерную матрицу (можно обрезать лишние элементы).

In [3]:
matrix = np.arange(1, 25).reshape(2, 12)

print("Исходная матрица 2 x 12:")
print(matrix)

reshaped_matrix = matrix.reshape(2, 3, 4)

print("\nТрёхмерная матрица")
print(reshaped_matrix)

Исходная матрица 2 x 12:
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]

Трёхмерная матрица 2 x 3 x 4:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


#### Операции с массивами

Выполните самостоятельно следующие задания:
1. Примените транспонирование к матрице (mat.T)
2. Найдите умножение 2-х матриц (np.dot(m1,m2)), сложение (add), вычитание (subtract), поэлементное умножение (m1*m2)
3. Вычислите скалярное произведение двух одномерных векторов

In [ ]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

transposed_mat = mat.T

print("Исходная матрица:")
print(mat)

print("\nТранспонированная матрица:")
print(transposed_mat)

Исходная матрица:
[[1 2 3]
 [4 5 6]]

Транспонированная матрица:
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
m1 = np.array([
    [1, 2],
    [3, 4]
])

m2 = np.array([
    [5, 6],
    [7, 8]
])

dot_product = np.dot(m1, m2)
matrix_sum = np.add(m1, m2)
matrix_diff = np.subtract(m1, m2)
elementwise_product = m1 * m2

print("Матрица 1:")
print(m1)

print("\nМатрица 2:")
print(m2)

print("\nУмножение матриц (np.dot):")
print(dot_product)

print("\nСложение матриц (np.add):")
print(matrix_sum)

print("\nВычитание матриц (np.subtract):")
print(matrix_diff)

print("\nПоэлементное умножение (m1 * m2):")
print(elementwise_product)

Матрица 1:
[[1 2]
 [3 4]]

Матрица 2:
[[5 6]
 [7 8]]

Умножение матриц (np.dot):
[[19 22]
 [43 50]]

Сложение матриц (np.add):
[[ 6  8]
 [10 12]]

Вычитание матриц (np.subtract):
[[-4 -4]
 [-4 -4]]

Поэлементное умножение (m1 * m2):
[[ 5 12]
 [21 32]]


In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

dot_product = np.dot(v1, v2)

print("Вектор 1:", v1)
print("Вектор 2:", v2)
print("Скалярное произведение:", dot_product)

Вектор 1: [1 2 3]
Вектор 2: [4 5 6]
Скалярное произведение: 32


Задания с мудл

Создайте два массива: один заполнен 0, второй - 1. Объедините их и перемешайте.

In [ ]:
zeros_array = np.zeros(10, dtype=int)
ones_array = np.ones(10, dtype=int)

combined_array = np.concatenate((zeros_array, ones_array))
np.random.shuffle(combined_array)

print("Массив из нулей:", zeros_array)
print("Массив из единиц:", ones_array)
print("Объединенный и перемешанный массив:", combined_array)

Массив из нулей: [0 0 0 0 0 0 0 0 0 0]
Массив из единиц: [1 1 1 1 1 1 1 1 1 1]
Объединенный и перемешанный массив: [1 0 1 1 1 1 1 0 0 1 0 1 0 1 1 0 0 0 0 0]


Создать матрицу размера 40*25, составленную из чисел 0 (с вероятностью появления 0.4), 1 (с вероятностью появления 0.25), 2 (с вероятностью появления 0.25) и 3 (остальная доля). Выведите всю матрицу.

In [ ]:
rows = 40
cols = 25

probabilities = [0.4, 0.25, 0.25, 0.1]

matrix = np.random.choice([0, 1, 2, 3], size=(rows, cols), p=probabilities)

print("Матрица 40x25:")
matrix

Матрица 40x25:


array([[0, 0, 0, 2, 0, 1, 0, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 3, 1, 3, 1, 2,
        0, 0, 0],
       [0, 0, 0, 1, 0, 2, 1, 0, 1, 0, 1, 3, 0, 2, 0, 2, 0, 0, 1, 0, 2, 0,
        2, 0, 2],
       [3, 0, 1, 1, 1, 0, 3, 1, 2, 2, 0, 2, 0, 2, 1, 2, 2, 2, 1, 3, 1, 1,
        1, 0, 0],
       [2, 0, 1, 1, 0, 0, 1, 1, 1, 2, 2, 1, 2, 0, 1, 2, 2, 2, 0, 3, 2, 3,
        0, 2, 0],
       [1, 0, 2, 2, 1, 1, 0, 2, 1, 2, 2, 3, 2, 0, 0, 2, 0, 1, 0, 0, 0, 2,
        0, 0, 3],
       [2, 0, 0, 1, 1, 0, 3, 1, 1, 1, 2, 0, 0, 0, 0, 3, 2, 1, 0, 0, 0, 1,
        0, 2, 0],
       [0, 0, 0, 2, 1, 1, 2, 3, 0, 2, 0, 0, 2, 0, 0, 1, 2, 1, 2, 0, 2, 0,
        3, 2, 0],
       [3, 2, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 2, 0, 1, 0, 2, 0, 1, 0, 0, 1,
        0, 3, 2],
       [2, 3, 0, 1, 1, 3, 0, 0, 0, 0, 3, 2, 2, 0, 1, 0, 1, 3, 2, 0, 3, 0,
        3, 3, 2],
       [1, 2, 0, 2, 1, 0, 0, 0, 3, 1, 1, 1, 0, 0, 2, 0, 1, 0, 0, 2, 3, 3,
        3, 2, 0],
       [0, 1, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0,
      

Создайте три одномерных массива, заполненных случайными числами (можно использовать какие-то распределения). Создайте из них две матрицы, объединив одномерные массивы по строкам и по столбцам соответственно.

In [ ]:
array1 = np.random.normal(0, 1, 5)
array2 = np.random.randint(0, 10, 5)
array3 = np.random.uniform(0, 1, 5)

matrix_rows = np.vstack((array1, array2, array3))
matrix_cols = np.hstack((array1, array2, array3))

print("Массив 1 (нормальное распределение):", array1)
print("Массив 2 (случайные целые числа):", array2)
print("Массив 3 (равномерное распределение):", array3)
print("\nМатрица, объединенная по строкам:")
print(matrix_rows)
print("\nМатрица, объединенная по столбцам:")
print(matrix_cols)

Массив 1 (нормальное распределение): [-1.98079647  0.73195548 -0.55144918 -0.75213371 -1.06136058]
Массив 2 (случайные целые числа): [3 2 3 1 1]
Массив 3 (равномерное распределение): [0.22927609 0.68541493 0.52641254 0.55005451 0.83223886]

Матрица, объединенная по строкам:
[[-1.98079647  0.73195548 -0.55144918 -0.75213371 -1.06136058]
 [ 3.          2.          3.          1.          1.        ]
 [ 0.22927609  0.68541493  0.52641254  0.55005451  0.83223886]]

Матрица, объединенная по столбцам:
[-1.98079647  0.73195548 -0.55144918 -0.75213371 -1.06136058  3.
  2.          3.          1.          1.          0.22927609  0.68541493
  0.52641254  0.55005451  0.83223886]


Создайте матрицу размера 100*20, заполните её числами 0, 1, 2, ... Перемешайте матрицу и выведите. Разделите матрицу по столбцам по 4. Разделите матрицу по строкам по 10.

In [4]:
matrix = np.arange(100 * 20).reshape(100, 20)

np.random.shuffle(matrix)
np.random.shuffle(matrix.T)


column_blocks = [matrix[:, i:i+4] for i in range(0, 20, 4)]


row_blocks = [matrix[i:i+10, :] for i in range(0, 100, 10)]


print("Исходная матрица (первые 5 строк и 5 столбцов):")
print(matrix[:5, :5])

print("\nБлоки по столбцам (первый блок):")
print(column_blocks[0])

print("\nБлоки по строкам (первый блок):")
print(row_blocks[0])

Исходная матрица (первые 5 строк и 5 столбцов):
[[ 893  898  888  883  887]
 [ 693  698  688  683  687]
 [1013 1018 1008 1003 1007]
 [ 313  318  308  303  307]
 [ 473  478  468  463  467]]

Блоки по столбцам (первый блок):
[[ 893  898  888  883]
 [ 693  698  688  683]
 [1013 1018 1008 1003]
 [ 313  318  308  303]
 [ 473  478  468  463]
 [1053 1058 1048 1043]
 [ 213  218  208  203]
 [ 953  958  948  943]
 [ 513  518  508  503]
 [ 773  778  768  763]
 [ 833  838  828  823]
 [1653 1658 1648 1643]
 [ 813  818  808  803]
 [ 433  438  428  423]
 [1873 1878 1868 1863]
 [1633 1638 1628 1623]
 [1153 1158 1148 1143]
 [ 373  378  368  363]
 [ 613  618  608  603]
 [1353 1358 1348 1343]
 [1213 1218 1208 1203]
 [1773 1778 1768 1763]
 [1733 1738 1728 1723]
 [ 913  918  908  903]
 [ 393  398  388  383]
 [1893 1898 1888 1883]
 [ 453  458  448  443]
 [1493 1498 1488 1483]
 [ 573  578  568  563]
 [ 133  138  128  123]
 [1853 1858 1848 1843]
 [ 853  858  848  843]
 [1533 1538 1528 1523]
 [ 793  798  788  

Преобразуйте матрицу из предыдущего задания в одномерный массив. Сделайте выборку из него, задав произвольную шкалу вероятностей вхождения 7-ми различных элементов. Размер массива оставить прежним.

In [7]:
matrix = np.arange(100 * 20).reshape(100, 20)
flattened_array = matrix.flatten()

elements = [0, 1, 2, 3, 4, 5, 6]
probabilities = [0.1, 0.2, 0.3, 0.1, 0.1, 0.1, 0.1]

sampled_array = np.random.choice(elements, size=flattened_array.size, p=probabilities)

sampled_matrix = sampled_array.reshape(100, 20)

print("Одномерный массив (первые 10 элементов):")
print(flattened_array[:10])

print("\nВыборка (первые 10 элементов):")
print(sampled_array.size)

print("\nМатрица после выборки (первые 5 строк и 5 столбцов):")
print(sampled_matrix.shape)

Одномерный массив (первые 10 элементов):
[0 1 2 3 4 5 6 7 8 9]

Выборка (первые 10 элементов):
2000

Матрица после выборки (первые 5 строк и 5 столбцов):
(100, 20)
